### ISSUE TITLE
Integrity issues with uploads/downloads

### ISSUE THREAD

**Issue by pfuentes69** [jhalter/mobius#7]
Hello,
first of all, thanks a lot for this project.
This is more a help request that a bug report.
I built a server on Linux (AWS), which is available at hotline.retrobyt.es and it works fine, but we are experiencing issues with the integrity of files. In many cases the downloads will not have the same size and/or will fail when opening (i.e. trying to uncompress SIT files or trying to mount disk images).
Is this a common problem? Is there anything we should do to improve it in the sever config?
Thanks again!
Pedro

**Comment by jhalter** [comment]
Hi Pedro,
Thanks for the feedback.  

For .sit/.img files that fail when opening, do they still fail if you drag and drop them on to Stuffit Expander or Disk Copy?

**Comment by jhalter** [comment]
Hi, I downloaded a few random files from hotline.retrobyt.es and was able to uncompress/mount them with manually drag and drop, but if you'd like to create account so that I can try upload/download that'd be great.  If you can point me at any examples of bad files that would also help.  Also could you tell me which client version and OS you're using?

Regarding file metadata, the current implementation is that when a file is uploaded the creator/type metadata and comments will be lost, as I don't think there is a way to preserve the data stored in the Mac resource fork on unix filesystems.  During file download, for a few well known file extensions like `.sit`, `.jpg`, `.pdf`, the server will include the Mac creator/type information.  Maybe there's a better solution?  Need to investigate more.

I've been planning to move this mapping to an external config file and add more mappings, but I've been lazy.  It shouldn't be difficult though, so I'll try to get that done soon.

**Comment by pfuentes69** [comment]
Hello,
This doesn't happen always. I think I cleaned most of the files that later I couldn't download, so it can happen that existing files are mostly OK.
For example, I tried to upload now a game (English / Games / out_of_this_world.sit). This SIT expands properly on my Mac, but the downloaded copy seems to be corrupted.
I understand the metadata can be lost... that's assumed as it happens quite often (i.e. with FTP), but the lack of integrity is trickier.

**Comment by pfuentes69** [comment]
Hello again
I'm doing more tests and I think it could be some weirdness of the Stuffit version I'm using.
If I compress a folder with certain version, upload it and download it, it seems fine, but when I upload some SIT files that I can expand, then when upload and download, then in some cases is corrupted
I don't know if you will find anything strange, but definitely I need to do more tests to reproduce the problem more consistently.

**Comment by jhalter** [comment]
Thanks for the sample file.  I compared with a known good version of the file from Macintosh Garden with a hex editor and there's definitely something wrong that is causing the first 10 bytes to be overwritten with junk.

**Comment by pfuentes69** [comment]
But can you reproduce the issue uploading and downloading some known good version?

**Comment by jhalter** [comment]
I figured out that the problem occurs when uploading any file that contains a comment.  

The bug is that I'm not considering the length of the comment as part of the length of the file header, so when a file has a comment the comment bytes are appended at the beginning of the file.  Oops.  

I have a fix ready, will push it later tonight.

**Comment by pfuentes69** [comment]
Wow! That was a sneaky bug!
Fantastic!

**Comment by jhalter** [comment]
Ok, I think this should be fixed now in v0.0.15:  https://github.com/jhalter/mobius/releases/tag/v0.0.15

Let me know if you still run into problems.  Cheers!

**Comment by pfuentes69** [comment]
Hello,
thanks a lot for your reactivity!

I deployed the new version, and I'm doing tests... I still have problems, but this is so weird that I can't confirm if the problem is mine or not. 

For example... If I try again with the same SIT file (Out of this world game), I have the same issue. The download can't be expanded. I tried two versions, one with a comment and other without comment, and both failed, and what I see now is that all the downloads (indistinctly if the upload had a comment or not) now seem to have the comment "TODO".  

But the weird thing is that if I expand the SIT on my computer, then compress it again, upload it, download it and expand it, then all seems OK.

Therefore, while I definitely have problems, I can't say if it's in the server or on my side.

**Comment by pfuentes69** [comment]
Hello again,
well... definitely there's some problem with my setup.

I installed a different version of StuffIt and now I can expand the download that was giving me issues. I still don't understand why the original on my disk could be expanded, and not the download, but the Stuffit version changed that.

So... I want to believe that this was not to make you waste your time, because you found that issue with the comments, but the root cause seems to be some weirdness on my side.

Anyway, just in case... I still notice that all downloads have this "TODO" string in the comment and I also noticed that I can't change the comments from the Hotline client.

Thanks!

**Comment by jhalter** [comment]
Hi Pedro, for the version of out_of_this_world.sit that cannot be expanded, are you certain that it was not already corrupted by the comment bug?  Maybe you could compare the md5 checksum from MacintoshGarden with the file you have?

Regarding the TODO comment, that's a hardcoded placeholder that is returned by the server for all files.  Right now it's not possible to set or change that, but I can remove it if you find it annoying.  I have some ideas on how I might add support for comments without resource forks by storing them somewhere external to the file, but I haven't started work on it yet.

If you still suspect you are seeing corruption after further tests, let me know and I'd be happy to investigate further.  I'll see if I can setup some automated tests as well.

**Comment by pfuentes69** [comment]
Hello!
what puzzles me is that, using the StuffIt version I had previously, the original could be expanded without trouble, but when uploading/downloading, then I couldn't do it.   And now that I'm using a newer version of StuffIt Expander, then the same download that failed before (and keeps failing if I use the previous StuffIt), it's working fine... Really weird.

I'll do definitely more tests in the next days, using both clients 1.2.3 and 1.9, but right now it seems it was some crazy side effect of my particular setup. 

About the comments, for me this is not a big deal at all. Maybe I'd prefer that comments are just left empty, but knowing this is a known limitation it's fine.

Thanks!

**Comment by pfuentes69** [comment]
Right now I can't say... let's see if I can reproduce this consistently when I try in a different machine. That machine is a real Mac that has the same disk image that I have in the emulator, and there I didn't install yet the new StuffIt... I'll see if it happens the same thing again or not.
Txs

**Comment by jhalter** [comment]
Hi Pablo, I spent some time playing with Hotline over the weekend and fixed a couple issues with file transfers that may cause the server to panic.  Not sure if this could cause the problems you're seeing, but it might help.

The fixes are in [v0.2.1](https://github.com/jhalter/mobius/releases/tag/v0.2.1)

**Comment by pfuentes69** [comment]
Hi there,
I couldn't reproduce my weird problems after reinstalling StuffIt, so it seems it was something on my side. 
Anyway, I'll install later today this version and I'll be glad to help with the tests. 
Thanks!

**Comment by jhalter** [comment]
Sorry about that, should be fixed in:

https://github.com/jhalter/mobius/releases/tag/v0.2.3

I've been testing on OSX but for some reason could only reproduce that problem on Linux.

**Comment by pfuentes69** [comment]
Hey, no worries at all!

I updated it and new version seems just fine. Let me know if you want me to test any other thing.

Txs!

**Comment by pfuentes69** [comment]
Hello,
yes, I noticed that when using a real classic Mac with poor connectivity, where the transfers failed a few times. Knowing if the transfer was completed successfully wasn't evident.
I'd be glad to test that when/if done.
Txs!

**Comment by jhalter** [comment]
Hi, I've built a new release with file and folder transfer resume if you'd like to try it:

https://github.com/jhalter/mobius/releases/tag/v0.3.0

The new behavior is that partial files are stored with a temp file with an `.incomplete` file suffix, which is removed after the transfer completes.  From the perspective of the Hotline client, the extension is hidden but if you look at the filesystem directly you'll see it.  There are a few edge cases to follow up on, but it seems like it works in my testing so far.

This should help to clearly distinguish between complete and partially transferred files.  Please let me know if you run into any problems.

**Comment by jhalter** [comment]
Marking this as closed, but reach out if you run into problems
