### ISSUE TITLE
GtkHx on IRIX malfunctions

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#78]
Hi!

This might be a really odd client, but it’s more or less the only one working on older proprietary UNIX operating systems such as IRIX and SUN Solaris. Getting some strange functionality from it. User list doesn’t quite populate and writing in the chat only creates server type messages. Nothing gets posted into the actual chat. I took a screenshot to show you the error messages at the top. I also logged into your Mobius server, so if you log errors you might see something there. 

![9DF9A682-B107-42FE-A1FE-54562F505835](https://user-images.githubusercontent.com/27211475/202867036-c710dc5a-ff76-4042-841a-298f357b6bdf.jpeg)

**Comment by jhalter** [comment]
Oh wow, that’s an obscure one.  Any idea if Gtkhx works on other platforms?  Or hx, even? 

I’ll see if I can spin something up to test in Qemu.

**Comment by Knezzen** [comment]
The website is still around, so you can get it to compile if you find all the old dependencies. It’s an GTK 1 based client.

https://gtkhx.sourceforge.net/

**Comment by jhalter** [comment]
The chat bug is probably fixed in `v0.10.8`.

**Comment by Knezzen** [comment]
Seems to be working (tried with your server). Still having issues with files, news and the user list though.

**Comment by jhalter** [comment]
Fixed in v0.10.9
